### ISSUE TITLE
Closing the game before Steps are saved to disc

### ISSUE THREAD

**Issue by Geldahar** [GrandTheftWalrus/RuneLite-World-Heatmap#6]
Will this cause the steps taken after the save but before closing the game to disappear or are they cached somewhere/saved upon closing? 

If they are deleted then i would like to set the value lower, i am only worried about wether this will cause any kind of lag.

**Comment by GrandTheftWalrus** [comment]
The heatmap steps are saved (to their .heatmap file) on logout, on plugin shutdown, and also on image write, so yee it's saved automatically upon closing. Also, the autosaving of the .heatmap file shouldn't cause any lag, it only takes like 20 ms (as opposed to writing the PNG which takes a few seconds). It's possible that Alt-F4ing might shut down runelite without running the plugin's shutdown function, but yee

**Comment by Geldahar** [comment]
I tried to convert the heatmap file into .png and it would not load. Not sure if thats still a bug. Ty for feedback

**Comment by GrandTheftWalrus** [comment]
@Geldahar Do you mean by pressing one of the "Write Heatmap Image" buttons? There are some users for whomst the image writing wasn't working, but I recently made an update which seems to have fixed it for them. The update still needs to be reviewed by the RuneLite devs before it'll be live, which will probs be another week or two.

**Comment by Geldahar** [comment]
Ok thank you, i will try it again but if not i will be looking forward to update. This is a really cool looking plugin!
