### ISSUE TITLE
The base map png is outdated

### ISSUE THREAD

**Issue by yrrah2** [GrandTheftWalrus/RuneLite-World-Heatmap#7]
I'd commit an updated map myself but I can't find where the base image is in this repo

It should include Varlamore, DT2 sites, and some others

**Comment by GrandTheftWalrus** [comment]
I started working on le new update again recently (I swear it's ready this time, again, just gotta test it) and it includes the rough draft version of Varlamore but I have to wait for [Explv ](https://github.com/Explv)to update his [full world map image generator](https://github.com/Explv/Explv.github.io) or figure out another way to get an updated world map with the correct resolution (the world map image hosted by jagex is 3 pixels per tile but the full map image I have is 4 pixels per tile) before I can properly put Varlamore and stuff in the image output

the rough draft version:
![image](https://github.com/GrandTheftWalrus/RuneLite-World-Heatmap/assets/70998757/da5cc0e4-acac-4e7e-8ab4-fafd2e9e8a82)

**Comment by GrandTheftWalrus** [comment]
Nevermind I figured it out and varlamore will be on the map in the upcoming update
