### ISSUE TITLE
Heatmap Images folder has to be manually created

### ISSUE THREAD

**Issue by vartan** [GrandTheftWalrus/RuneLite-World-Heatmap#8]
I am running the new version of the plugin on MacOS. Nothing was happening when I would try to save a heatmap image. Looking at the code, I saw it saves them in a "Heatmap Images" subdirectory. Once I created this folder, it was writing tif images, but they were corrupted. I tried adjusting the speed-memory tradeoff to 4 and then it saved as expected.

**Comment by GrandTheftWalrus** [comment]
![1ii97rqnqj091](https://github.com/GrandTheftWalrus/RuneLite-World-Heatmap/assets/70998757/0ab948a6-573f-4aa1-8280-b2f9f7659e8e)

Balls. Just fixed the directory creation and changed the default speed-memory tradeoff from 6 to 4 and made a new PR. It might be about 2 weeks before she goes through

**Comment by GrandTheftWalrus** [comment]
She's fixed now. The RuneLite crew put the PR through real quick
